{
 "title": "Concrete Strength Analysis",
 "tags": [
  "concrete",
  "dataset2"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Minimal/optimal composition of concrete mixture",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT min(cement) AS cement, min(water) AS water, min(coarse_aggregate) AS coarse_aggregate, min(Superplasticizer) AS superplasticizer, strength FROM beton.concrete_data WHERE strength = (SELECT MAX(strength) FROM beton.concrete_data) GROUP BY strength;"
    }
   ]
  },
  {
   "title": "Minimal Strength (MPa) by Age (days)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT age, min(strength) AS min_strength FROM concrete_data group by age ORDER BY age"
    }
   ]
  },
  {
   "title": "Cement (kg in a m^3 mixture) vs Minimal Strength (MPa)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT cement, min(strength) AS min_strength FROM concrete_data GROUP BY cement ORDER BY cement"
    }
   ]
  },
  {
   "title": "Water Content (kg in a m^3 mixture) vs Minimal Strength (MPa)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT water, min(strength) AS min_strength FROM concrete_data GROUP BY water  ORDER BY water"
    }
   ]
  },
  {
   "title": "Average Strength by Age",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT age, AVG(strength) AS avg_strength FROM concrete_data GROUP BY age ORDER BY age"
    }
   ]
  },
  {
   "title": "Dataset Summary",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "rawSql": "SELECT * FROM concrete_summary" }
   ]
  }
 ]
}